env:
  PCF_DESTINATION_API_ENDPOINT: https://api.us22-2-pcf1-system.oc.vmware.com
  PCF_SPACE: whiteboard-staging
  PCF_ORG: TxP
  PCF_DOMAIN: apps.scdc1.itcna.vmware.com
  WHITEBOARD_HOSTNAME: whiteboard-staging
  WHITEBOARD_MAILER_FROM_ADDRESS: txp-noreply@vmware.com
  WHITEBOARD_MAILER_URL: whiteboard-staging.apps.scdc1.itcna.vmware.com
  NEWRELIC_APP_NAME: whiteboard-staging
  ENVIRONMENT: staging
  CF_TEMP_DOMAIN: apps.scdc1.itcna.vmware.com
  TEMP_WHITEBOARD_HOSTNAME: whiteboard-staging-temp
steps:
  - name: build
    command: ./buildkite/scripts/build.sh
    timeout_in_minutes: 30
    plugins:
      - docker-compose#v3.0.3:
          run: app
          shell: false
          config: buildkite-docker-compose.yml
  - wait

  - name: deploy-maintenance
    command: ./buildkite/scripts/deploy-maintenance.sh
    agents:
      queue: "whiteboard"

  - wait

  - name: deploy-whiteboard
    command: ./buildkite/scripts/deploy.sh
    agents:
      queue: "whiteboard"

  - wait

  - name: acceptance-test
    command: ./buildkite/scripts/acceptance.sh
    agents:
      queue: "whiteboard"

  - wait

  - name: map-routes
    command: ./buildkite/scripts/map-routes.sh
    agents:
      queue: "whiteboard"