env:
  PCF_DESTINATION_API_ENDPOINT: https://api.us22-2-pcf1-system.oc.vmware.com
  PCF_SPACE: whiteboard-staging
  PCF_ORG: TxP
  PCF_DOMAIN: apps.scdc1.itcna.vmware.com
  WHITEBOARD_HOSTNAME: whiteboard-staging

steps:
  - name: build
    command: ./buildkite/scripts/build.sh
    timeout_in_minutes: 30
    plugins:
      - docker-compose#v3.0.3:
          run: app
          shell: false
          config: buildkite-docker-compose.yml
  - wait

  - name: deploy-maintenance
    command: ./buildkite/scripts/deploy-maintenance.sh
    agents:
      queue: "whiteboard"